# Generated by Django 4.2.23 on 2025-10-07 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='categories',
            name='name_hy',
        ),
        migrations.RemoveField(
            model_name='categories',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='products',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='products',
            name='description_hy',
        ),
        migrations.RemoveField(
            model_name='products',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='products',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='products',
            name='name_hy',
        ),
        migrations.RemoveField(
            model_name='products',
            name='name_ru',
        ),
    ]
