# Generated by Django 4.2.23 on 2025-10-10 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_remove_categories_name_en_remove_categories_name_hy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='name_en',
            field=models.CharField(max_length=150, null=True, unique=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='categories',
            name='name_hy',
            field=models.CharField(max_length=150, null=True, unique=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='categories',
            name='name_ru',
            field=models.CharField(max_length=150, null=True, unique=True, verbose_name='Название'),
        ),
    ]
