# Generated by Django 4.2.23 on 2025-10-10 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_categories_name_en_categories_name_hy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='products',
            name='description_hy',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='products',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='products',
            name='name_en',
            field=models.CharField(max_length=150, null=True, unique=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='products',
            name='name_hy',
            field=models.CharField(max_length=150, null=True, unique=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='products',
            name='name_ru',
            field=models.CharField(max_length=150, null=True, unique=True, verbose_name='Название'),
        ),
    ]
