# Generated by Django 4.2.23 on 2025-09-28 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_productimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ('-id',), 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
    ]
